Move update events from window to root container
inlet/react-pixi pull request #340
Opened 2022-04-29 10:20 UTC by Ledzz

**Description:**
I've didn't manage to get the canvas instance from the hostconfig where events were emitted from, so I've basically done what react-three-fiber does: I store the root container in each pixi component. Not so elegant solution, but iterating through all branch of the tree to find root node seems a bit overhead. Also, I didn't add any new tests, bc I don't see any necessity.
Maybe I should leave old window.dispatchEvent for backwards compatibility? Ideally I'd hide this behind some kind of global flag, but I don't know how to do it good.

**Related issue (if exists):**
#339

2022-04-29 10:30 UTC, Ledzz commented
I think I also need to update the docs. But I will do it after @inlet confirms the changes are OK.

2022-05-02 09:01 UTC, inlet requested changes
Looks good @Ledzz

Could you also add tests with multiple renderers, thanks in advance!
And yes please update the docs with this

2022-05-06 14:34 UTC, inlet approved these changes
Looks good!

Thanks

2022-05-16 11:46 UTC, saitonakamura commented
@inlet can you merge it and release a new version?

2022-05-18 14:10 UTC, inlet commented
@saitonakamura will do that tomorrow

2022-05-20 08:01 UTC, merged